In [2]:
# Some messy code to calculate relationships between lone-pair energies and optimal bonded-pair-only energies.

import json
import csv
import pandas as pd
import numpy as np

with open('data/result_vsepr_cli.json') as f:
    data = json.load(f)

rows = []
for obj in data:
    for run in obj['runs']:
        rows.append({
            'bonded_points': obj['bonded_points'],
            'lone_points': obj['lone_points'],
            'energy': run['energy']
        })

vsepr = pd.DataFrame(rows)
optimal = pd.read_csv('data/energies.csv', sep=',')

optimal

     n       energy
0    2     0.500000
1    3     1.732051
2    4     3.674235
3    5     6.474691
4    6     9.985281
5    7    14.452977
6    8    19.675288
7    9    25.759987
8   10    32.716949
9   11    40.596451
10  12    49.165253
11  13    58.853231
12  14    69.306363
13  15    80.670244
14  16    92.911655
15  17   106.050405
16  18   120.084467
17  19   135.089468
18  20   150.881568
19  21   167.641623
20  22   185.287536
21  23   203.930191
22  24   223.347074
23  25   243.812760
24  26   265.133326
25  27   287.302615
26  28   310.491542
27  29   334.634678
28  30   359.603946
29  31   385.530838
30  32   412.261275
31  33   440.204059
32  34   468.904853
33  35   498.569874
34  36   529.122408
35  37   560.618888
36  38   593.038504
37  39   626.389009
38  40   660.675279
39  41   695.916744
40  42   732.078108
41  43   769.190847
42  44   807.174263
43  45   846.188401
44  46   886.170218
45  47   927.059271
46  48   968.713455
47  49  1011.557184
48  50  1055.182315
49  51  1099.819292
50  52  1145.418970
51  53  1191.922298
52  54  1239.361481
53  55  1287.777033

In [12]:
min_vsepr = vsepr[vsepr['lone_points'] == 0].groupby('bonded_points').min().reset_index()[:54]
min_vsepr['energy_diff'] = min_vsepr.apply(
    lambda row: row['energy'] - optimal.loc[optimal['n'] == row['bonded_points'], 'energy'].item(),
    axis=1
).clip(lower=0).round(8)

ValueError: can only convert an array of size 1 to a Python scalar

In [4]:
with open('data/lone_pair_energies.json') as f:
    data = json.load(f)

rows = []
for obj in data:
    rows.append({
        'bonded_points': obj['bonded_points'],
        'lone_points': obj['lone_points'],
        'energy': obj['best_energy']
    })

lone_vsepr = pd.DataFrame(rows)
lone_vsepr

     bonded_points  lone_points     energy
0                2            3   8.360773
1                2            4  13.286213
2                2            5  19.590620
3                3            3  12.402231
4                3            4  18.470925
..             ...          ...        ...
148              0            4   5.582045
149              0            5   9.836612
150              1            3   5.051613
151              1            4   9.078569
152              1            5  14.208840

[153 rows x 3 columns]

In [5]:
lone_2 = vsepr[vsepr['lone_points'] == 2].groupby('bonded_points').min().sort_values('bonded_points').reset_index()[['bonded_points', 'energy']][:51]
lone_3 = lone_vsepr[lone_vsepr['lone_points'] == 3][['bonded_points', 'energy']].sort_values('bonded_points').reset_index()
lone_4 = lone_vsepr[lone_vsepr['lone_points'] == 4][['bonded_points', 'energy']].sort_values('bonded_points').reset_index()
lone_5 = lone_vsepr[lone_vsepr['lone_points'] == 5][['bonded_points', 'energy']].sort_values('bonded_points').reset_index()

In [18]:
diff_df = optimal[['n', 'energy']].rename(columns={'energy': 'energy_0'})[:54]
diff_df['two_diff'] = np.concat([lone_2['energy'].values - diff_df[:51]['energy_0'].values, [0] * 3]).astype('double')
diff_df['three_diff'] = np.concat([[0] * 1, lone_3['energy'].values - diff_df[1:52]['energy_0'].values, [0] * 2]).astype('double')
diff_df['four_diff'] = np.concat([[0] * 2, lone_4['energy'].values - diff_df[2:53]['energy_0'].values, [0] * 1]).astype('double')
diff_df['five_diff'] = np.concat([[0] * 3, lone_5['energy'].values - diff_df[3:54]['energy_0'].values]).astype('double')

diff_df

     n     energy_0   two_diff  three_diff  four_diff  five_diff
0    2     0.500000   0.259620    0.000000   0.000000   0.000000
1    3     1.732051   0.566070    0.899351   0.000000   0.000000
2    4     3.674235   0.882916    1.377379   1.907811   0.000000
3    5     6.474691   1.220170    1.886081   2.603877   3.361921
4    6     9.985281   1.573414    2.416949   3.300931   4.223559
5    7    14.452977   1.904171    2.940586   4.017947   5.137642
6    8    19.675288   2.301060    3.513489   4.762230   6.066017
7    9    25.759987   2.669705    4.067977   5.509204   6.989321
8   10    32.716949   3.052208    4.640157   6.271129   7.945559
9   11    40.596451   3.424161    5.202469   7.028813   8.897700
10  12    49.165253   3.824454    5.799326   7.819408   9.879755
11  13    58.853231   4.179771    6.351628   8.566437  10.828984
12  14    69.306363   4.587729    6.932069   9.349850  11.812168
13  15    80.670244   4.964202    7.511418  10.128967  12.791084
14  16    92.911655   5.361999    8.135985  10.926927  13.762792
15  17   106.050405   5.780482    8.740668  11.738595  14.783005
16  18   120.084467   6.187909    9.344809  12.555420  15.810770
17  19   135.089468   6.575060    9.933536  13.338135  16.786984
18  20   150.881568   6.993295   10.559828  14.167907  17.825858
19  21   167.641623   7.390447   11.156053  14.974167  18.830336
20  22   185.287536   7.811419   11.783691  15.807299  19.871477
21  23   203.930191   8.209718   12.383623  16.602416  20.874255
22  24   223.347074   8.632893   13.017804  17.446033  21.929023
23  25   243.812760   9.027816   13.615369  18.253703  22.931998
24  26   265.133326   9.441944   14.228886  19.075476  23.956540
25  27   287.302615   9.866937   14.870603  19.920176  25.016903
26  28   310.491542  10.274161   15.482024  20.735583  26.041077
27  29   334.634678  10.670999   16.094153  21.549496  27.062049
28  30   359.603946  11.103786   16.731083  22.394797  28.115056
29  31   385.530838  11.518805   17.346386  23.236752  29.161787
30  32   412.261275  11.949657   17.993708  24.087936  30.235535
31  33   440.204059  12.325569   18.580144  24.881564  31.223694
32  34   468.904853  12.760194   19.215825  25.713964  32.267124
33  35   498.569874  13.163088   19.834216  26.552532  33.326846
34  36   529.122408  13.589475   20.474088  27.395432  34.384981
35  37   560.618888  14.021096   21.118826  28.244775  35.429861
36  38   593.038504  14.448863   21.733697  29.087949  36.505002
37  39   626.389009  14.876148   22.386924  29.946460  37.553489
38  40   660.675279  15.303982   23.028519  30.798783  38.619862
39  41   695.916744  15.722192   23.659967  31.651384  39.673170
40  42   732.078108  16.148163   24.293208  32.491812  40.734292
41  43   769.190847  16.565500   24.927396  33.334167  41.787265
42  44   807.174263  17.001766   25.563166  34.183894  42.858087
43  45   846.188401  17.418976   26.201994  35.042483  43.912836
44  46   886.170218  17.827752   26.830349  35.881890  44.979135
45  47   927.059271  18.244713   27.458589  36.726285  46.023854
46  48   968.713455  18.703775   28.129152  37.599123  47.129357
47  49  1011.557184  19.119245   28.756215  38.436268  48.166633
48  50  1055.182315  19.548865   29.396713  39.293040  49.238249
49  51  1099.819292  19.967213   30.024989  40.135127  50.293647
50  52  1145.418970  20.400479   30.670441  41.005374  51.372323
51  53  1191.922298   0.000000   31.304691  41.848674  52.445982
52  54  1239.361481   0.000000    0.000000  42.720472  53.513043
53  55  1287.777033   0.000000    0.000000   0.000000  54.600579

In [21]:
from scipy.stats import linregress

two_lone_stats = linregress(diff_df['n'][:51].values, diff_df['two_diff'][:51].values)
three_lone_stats = linregress(diff_df['n'][1:52].values, diff_df['three_diff'][1:52].values)
four_lone_stats = linregress(diff_df['n'][2:53].values, diff_df['four_diff'][2:53].values)
five_lone_stats = linregress(diff_df['n'][3:54].values, diff_df['five_diff'][3:54].values)

In [22]:
for i in [two_lone_stats, three_lone_stats, four_lone_stats, five_lone_stats]:
    print(f'y = {i.slope:.8f}x + {i.intercept:.8f}, r={i.rvalue:.4f}, p={i.pvalue:.4e}, with error {i.stderr:.8f}.')

y = 0.40801029x + -1.02874777, r=0.9997, p=5.8669e-81, with error 0.00140479.
y = 0.61478526x + -1.55621878, r=0.9998, p=1.1603e-83, with error 0.00186404.
y = 0.82298731x + -2.08135991, r=0.9998, p=6.4415e-86, with error 0.00224426.
y = 1.03222528x + -2.59482775, r=0.9998, p=6.8041e-88, with error 0.00256514.

In [10]:
# Regression on the slopes
slope_regression = linregress([2, 3, 4, 5], [two_lone_stats.slope, three_lone_stats.slope, four_lone_stats.slope, five_lone_stats.slope])
print(f'Slope regression: y = {slope_regression.slope:.8f}x + {slope_regression.intercept:.8f}, r={slope_regression.rvalue:.4f}, p={slope_regression.pvalue:.4e}, with error {slope_regression.stderr:.8f}.')

Slope regression: y = 0.20808470x + -0.00879443, r=1.0000, p=3.5202e-06, with error 0.00039042.

α (mn term): 0.15755964
β (n² term): 0.16774382
R²: 0.690811